### ISSUE TITLE
Delete your own photos

### ISSUE THREAD

**Issue by selbekk** [selbekk/reecap#29]
As a user I want to be able to delete my own photos.

**Comment by selbekk** [comment]
In order to make this work without creating an account (will come later), I'm suggesting we create something called delete keys to handle this. Basically, the idea is:

1. When an image is uploaded and saved to the DB, a UUID `deleteKey` is created and returned to the user.
2. This key is saved to the user's localStorage in a key-value store that connects the image ID to the delete key.
3. When the user wants to delete an image, the app will find the delete key matching the image, and send a delete request to the server.
4. The server will delete the image and everything is good.

**Comment by chrisbolum** [comment]
Sounds good - though I'm not sure exactly how it works :P

**Comment by selbekk** [comment]
@chrisbolum hehe no from point of view of the user, this is going to be super simple. you click an image, click the delete button, and you're done.

Just needed to write down the approach I thought out before I forgot about it.

**Comment by selbekk** [comment]
there's still one bug left: 

- when you delete a photo, it's not removed from the gallery view you're currently viewing. Go to the next image, or if it's the last image - return to the main view
