### ISSUE TITLE
Implement "How it works" to Reecap

### ISSUE THREAD

**Issue by chrisbolum** [selbekk/reecap#57]

**Comment by selbekk** [comment]
In order for this not to look completely crazy on desktops, I'm adding some basic styles for larger viewports as well.

**Comment by selbekk** [comment]
Are these the texts we want though? I think there's a lot of focus on the pin code - perhaps a bit too much.

They can always change later, but yeah - think it through :)

**Comment by chrisbolum** [comment]
Haha - your first comment: Good point!

Second comment: yes, we should optimize the text later as we get feedback. The thought for the first draft was to use a "playful" tone while making sure the user doesn't forget the PIN :) Let's use this one for now, and then we can see - there will most likely come more visual elements as well to that part.

**Comment by selbekk** [comment]
Fair enough.

We should probably look into designing some real nice landing pages for when you've created an event, to make it as easy as possible to get the PIN to the People™. Create another task for that perhaps?

**Comment by chrisbolum** [comment]
For sure! A lot of improvements to the UI/UX now that we have gotten the first beta out :)
