### ISSUE TITLE
Reecap didn't work on Samsung S7

### ISSUE THREAD

**Issue by chrisbolum** [selbekk/reecap#60]
Strange..need some investigation!

**Comment by chrisbolum** [comment]
Samsung S7 Edge is released with Android version 6.0.1 (Marshmallow)

**Comment by selbekk** [comment]
what didn't work?

Kristofer Selbekk
Ph: +1 (510) 423-2212
(sent from my phone)

On 02 May 2016, at 15:00, chrisbolum <notifications@github.com<mailto:notifications@github.com>> wrote:


Samsung S7 Edge is released with Android version 6.0.1 (Marshmallow)

-

**Comment by chrisbolum** [comment]
They managed to view the PIN-screen, but nothing happened when they entered PIN. Typed in full URL, then the header and event title showed, but images were not loading or showing.

**Comment by selbekk** [comment]
Alrighty! What browser did they use? The standard browser or google chrome?

**Comment by chrisbolum** [comment]
Standard browser I would guess, as none of them are very tech-savvy..

**Comment by selbekk** [comment]
OK. Tried with S5 and S6 through BrowserStack, and that worked well. I'll see if I can stop by a phone shop and test it out there.

**Comment by selbekk** [comment]
Tested today on a demo Galaxy S7 edge with the standard browser, and there was indeed an error. Not sure how to fix it though - I'll look into it!

**Comment by selbekk** [comment]
I'm really not sure how to debug this without the real device. I'll see if I know anyone with the device, so that I can test it out and try!
