### ISSUE TITLE
Change text

### ISSUE THREAD

**Issue by chrisbolum** [selbekk/reecap#79]
For creating event, the help text for the input field is currently "What's your event called?"

Change to "Event name"

**Comment by selbekk** [comment]
Sure? I kind of like having labels in forms sound like a conversation vs the rigid question answer routine.

The decision is yours - just wondering about your reasoning!

**Comment by chrisbolum** [comment]
The reasoning was basically to shorten the text - I agree to the tone of voice, more of a conversation just like the "How it works" text. OK, I will see if I find another way of shorten it, leave it for now ;)
