### ISSUE TITLE
Usage analytics

### ISSUE THREAD

**Issue by chrisbolum** [selbekk/reecap#81]
Make a UI to access insights such as:
- # of events created in total
- # of pics uploaded in total
- # of pics uploaded on average per event
- # of users in total (one user = contributed with at least one pic)
- # of users on average per event

All of the metrics are valuable to access on two levels: (1) total in reecap, and (2) within a given timeframe - from date;to date

**Comment by selbekk** [comment]
I think we can get most of this information either through google analytics or firebase. I'll get in touch with you about login details to the latter @chrisbolum
