### ISSUE TITLE
Zeplin adjustments: front screen

### ISSUE THREAD

**Issue by chrisbolum** [selbekk/reecap#85]
See comments:

https://app.zeplin.io/project.html#pid=56dc15b932de870c432a7ada&sid=5727295fe137fb3075b2b0c6&ref=slack

**Comment by selbekk** [comment]
Hva gjenstår på denne @chrisbolum ?

**Comment by chrisbolum** [comment]
Om blåfargen og pixelene er endret til riktig så er den done ;)

**Comment by selbekk** [comment]
Det er fiksa :+1:
